# Generated by Django 3.2.7 on 2023-02-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(null=True, upload_to='business_units/')),
                ('idea_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('identified_problem', models.CharField(max_length=1000)),
                ('proposed_solution', models.CharField(max_length=1000)),
                ('benefit_of_solution', models.CharField(max_length=1000)),
                ('similar_solutions', models.CharField(max_length=1000, null=True)),
                ('attachment', models.FileField(null=True, upload_to='submission_attachments/')),
                ('status', models.CharField(default='Review Pending', max_length=20)),
                ('remark', models.CharField(max_length=1000, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.businessunit')),
                ('ideator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
