# Generated by Django 3.2.7 on 2023-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Review Pending', max_length=20),
        ),
    ]
