# Generated by Django 3.2.7 on 2023-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
