# Generated by Django 3.2.17 on 2023-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230215_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='idea_champion',
            new_name='innovation_champion',
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='image',
            field=models.ImageField(null=True, upload_to='business_units/'),
        ),
    ]
