# Generated by Django 3.2.7 on 2023-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230112_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='image',
            field=models.ImageField(null=True, upload_to='business_units/'),
        ),
    ]
