# Generated by Django 3.2.17 on 2023-02-15 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20230216_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 21, 59, 57, 747973, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 22, 0, 15, 765408, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
