# Generated by Django 3.2.17 on 2023-02-15 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20230216_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 22, 29, 5, 307173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 22, 29, 5, 268185, tzinfo=utc)),
        ),
    ]
