# Generated by Django 3.2.7 on 2023-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_businessunit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attachments',
            field=models.FileField(null=True, upload_to='submission_attachments/'),
        ),
    ]
