# Generated by Django 3.2.17 on 2023-02-21 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20230216_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 43, 30, 585501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 11, 43, 30, 539041, tzinfo=utc)),
        ),
    ]
