# Generated by Django 3.2.7 on 2023-01-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_submission_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
