# Generated by Django 3.2.17 on 2023-02-21 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230221_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
