# Generated by Django 3.2.7 on 2023-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
